name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/gcc-ensibs/gcc-ensibs-website:${GITHUB_SHA::12}
          docker push ghcr.io/gcc-ensibs/gcc-ensibs-website:${GITHUB_SHA::12}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 'SSH Docker Compose Up'
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          key: ${{secrets.SSH_KEY}}
          script: |
            cd /home/new-website
            docker compose pull
            docker compose up -d --build --force-recreate
