name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/GCC-ENSIBS/gcc-ensibs-website:${GITHUB_SHA::12}
          docker push ghcr.io/gcc-ensibs/gcc-ensibs-website:${GITHUB_SHA::12}

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Copy SSH key to the server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "github_actions_ssh_key"
        target: "~/.ssh/"

    - name: Deploy to server
      run: |
        ssh -i ~/.ssh/github_actions_ssh_key ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker compose pull && docker compose up --build --force-recreate -d"
